---
indicator: submit
#auto_fieldset: { id: create-form }
action: '/tasks/create'
attributes:
    class: create-form
elements:
#subject
    - type: Text
      name: subject
      label: Subject
      attributes:
        title: Subject
      constraints:
        - Required
#description
    - type: Textarea
      name: description
      label: Description
#creator_id (for model)
    - type: Hidden
      name: creator_id
#creator
    - type: Text
      name: creator_name
      label: Creator
      attributes:
        readonly: readonly
#owner
    - type: Select
      name: owner_id
      label: Owner
#submit button
    - type: Submit
      name: submit
      value: Create
#      attributes:
output_processors:
    - Indent
