package Tasker::Model::TaskerDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Tasker::Schema',
    
    connect_info => {
        dsn         => 'dbi:mysql:tasker',
        user        => 'tasker_user',
        password    => 'tasker_password',
    }
);

=head1 NAME

Tasker::Model::TaskerDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Tasker>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Tasker::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.25

=head1 AUTHOR

Ilya A. Chesnokov

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
